-- chats
CREATE TABLE IF NOT EXISTS chats (
chat_uuid   UUID PRIMARY KEY,
user_id     BIGINT NOT NULL,
model_id    BIGINT NOT NULL REFERENCES bot_models(id),
title       TEXT NOT NULL,
is_deleted  BOOLEAN NOT NULL DEFAULT FALSE,
created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
deleted_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_chats_user_updated
  ON chats (user_id, updated_at DESC);


-- messages
CREATE TABLE IF NOT EXISTS messages (
  message_uuid         UUID PRIMARY KEY,
  chat_uuid            UUID NOT NULL REFERENCES chats(chat_uuid),
  role                 TEXT NOT NULL CHECK (role IN ('user', 'bot')),
  content              TEXT NOT NULL,
  model_id             BIGINT REFERENCES bot_models(id),
  reply_to_message_id UUID REFERENCES messages(message_uuid),
  is_deleted           BOOLEAN NOT NULL DEFAULT FALSE,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at           TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_messages_chat_created
  ON messages (chat_uuid, created_at);

CREATE INDEX IF NOT EXISTS idx_messages_reply_to
  ON messages (reply_to_message_id);

-- message_feedbacks
CREATE TABLE IF NOT EXISTS message_feedbacks (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY
               (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  message_uuid UUID NOT NULL REFERENCES messages(message_uuid),
  user_id      BIGINT NOT NULL,
  model_id     BIGINT NOT NULL REFERENCES bot_models(id),
  is_positive  BOOLEAN NOT NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, message_uuid)
);

CREATE INDEX IF NOT EXISTS idx_feedback_message
  ON message_feedbacks (message_uuid);
